"""
Regression tests for the Sep 26, 2026 multi-chain Phase 2, Step 5
(docs/26_MULTI_CHAIN_SCOPE.md): cross-store stock transfer.

A transfer moves real stock instantly from one store to another store in
the same chain, auto-creating the destination product if it doesn't
exist there yet, preserving the batch/expiry/cost/MRP exactly, and
recording an audit-log entry on BOTH the source and destination
pharmacy. is_cross_gstin is computed from the two stores' GSTINs and is
display-only in v1 — no challan/tax-invoice/e-way-bill document is
generated by this endpoint.
"""
import os
import uuid

import pytest
import requests

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')


class _Base:
    @pytest.fixture(autouse=True)
    def setup(self):
        self.session = requests.Session()
        self.session.headers.update({"Content-Type": "application/json"})
        self.suffix = uuid.uuid4().hex[:8]
        resp = self.session.post(f"{BASE_URL}/api/auth/register", json={
            "email": f"stocktransfer_{self.suffix}@pharmacy.com", "name": "Stock Transfer Admin",
            "password": "StockTransfer123", "phone": "9877700006",
            "pharmacy_name": f"Stock Transfer Pharmacy {self.suffix}", "address": "1 St",
            "city": "Testville", "state": "Karnataka", "pincode": "560001",
            "drug_license_number": f"DL-STOCKTRANSFER-{self.suffix}",
        })
        assert resp.status_code == 200, resp.text
        self.session.headers.update({"Authorization": f"Bearer {resp.json()['token']}"})

    def _set_own_gstin(self, gstin):
        resp = self.session.put(f"{BASE_URL}/api/settings", json={"general": {"gstin": gstin}})
        assert resp.status_code == 200, resp.text

    def _create_product_and_batch(self, qty=100, cost=20, mrp=40):
        sku = f"STOCKXFER-{self.suffix}-{uuid.uuid4().hex[:4]}"
        batch_no = f"STOCKXFER-B-{uuid.uuid4().hex[:6]}"
        prod = self.session.post(f"{BASE_URL}/api/products", json={
            "sku": sku, "name": "Stock Transfer Test Medicine", "category": "medicine",
            "gst_percent": 5, "units_per_pack": 1,
        })
        assert prod.status_code == 200, prod.text
        batch = self.session.post(f"{BASE_URL}/api/stock/batches", json={
            "product_sku": sku, "batch_no": batch_no,
            "expiry_date": "2030-01-01", "qty_on_hand": qty,
            "cost_price_per_unit": cost, "mrp_per_unit": mrp,
        })
        assert batch.status_code == 200, batch.text
        return sku, batch_no

    def _add_second_store(self, gstin=None):
        payload = {
            "name": f"Stock Transfer Second {self.suffix}", "address": "2 St",
            "city": "Testville", "state": "Karnataka", "pincode": "560002",
            "phone": "9877700007", "drug_license_number": f"DL-STOCKTRANSFER-2-{self.suffix}",
        }
        if gstin:
            payload["gstin"] = gstin
        store = self.session.post(f"{BASE_URL}/api/pharmacies/stores", json=payload)
        assert store.status_code == 200, store.text
        return store.json()["pharmacy_id"]


class TestCreateStockTransfer(_Base):
    def test_transfer_moves_stock_and_creates_product_at_destination(self):
        sku, batch_no = self._create_product_and_batch(qty=100)
        second_store_id = self._add_second_store()

        resp = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 30}],
        })
        assert resp.status_code == 200, resp.text
        data = resp.json()
        assert data["items"][0]["quantity"] == 30
        assert data["is_cross_gstin"] is False  # second store has no GSTIN set

        switch = self.session.post(f"{BASE_URL}/api/users/me/switch-store", json={
            "pharmacy_id": second_store_id})
        assert switch.status_code == 200, switch.text

        products = self.session.get(f"{BASE_URL}/api/products?page_size=50").json()
        rows = products.get('data', products) if isinstance(products, dict) else products
        assert any(p["sku"] == sku for p in rows)

    def test_cross_gstin_is_detected_when_gstins_differ(self):
        self._set_own_gstin("29AAAAA0000A1Z5")
        sku, batch_no = self._create_product_and_batch(qty=50)
        second_store_id = self._add_second_store(gstin="27BBBBB0000B1Z9")

        resp = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 10}],
        })
        assert resp.status_code == 200, resp.text
        assert resp.json()["is_cross_gstin"] is True

    def test_rejected_when_not_enough_stock(self):
        sku, batch_no = self._create_product_and_batch(qty=5)
        second_store_id = self._add_second_store()

        resp = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 999}],
        })
        assert resp.status_code == 400, resp.text

    def test_rejected_for_store_outside_chain(self):
        sku, batch_no = self._create_product_and_batch(qty=50)
        other = requests.post(f"{BASE_URL}/api/auth/register", json={
            "email": f"stockxferother_{self.suffix}@pharmacy.com", "name": "Other Admin",
            "password": "StockXferOther123", "phone": "9877700008",
            "pharmacy_name": f"Unrelated Pharmacy {self.suffix}", "address": "9 St",
            "city": "Testville", "state": "Karnataka", "pincode": "560009",
            "drug_license_number": f"DL-STOCKXFEROTHER-{self.suffix}",
        })
        assert other.status_code == 200, other.text
        other_session = requests.Session()
        other_session.headers.update({"Authorization": f"Bearer {other.json()['token']}"})
        other_pharmacy_id = other_session.get(f"{BASE_URL}/api/users/me/stores").json()[0]["pharmacy_id"]

        resp = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": other_pharmacy_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 10}],
        })
        assert resp.status_code == 403, resp.text

    def test_cashier_cannot_create_transfer(self):
        sku, batch_no = self._create_product_and_batch(qty=50)
        second_store_id = self._add_second_store()
        member = self.session.post(f"{BASE_URL}/api/users", json={
            "email": f"stockxfercashier_{self.suffix}@pharmacy.com", "name": "Cashier",
            "password": "Cashier12345", "role": "cashier",
        })
        assert member.status_code == 200, member.text

        cashier_session = requests.Session()
        cashier_session.headers.update({"Content-Type": "application/json"})
        login = cashier_session.post(f"{BASE_URL}/api/auth/login", json={
            "email": f"stockxfercashier_{self.suffix}@pharmacy.com", "password": "Cashier12345"})
        assert login.status_code == 200, login.text
        cashier_session.headers.update({"Authorization": f"Bearer {login.json()['token']}"})

        resp = cashier_session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 10}],
        })
        assert resp.status_code == 403, resp.text

    def test_creates_two_audit_log_entries_one_per_pharmacy(self):
        sku, batch_no = self._create_product_and_batch(qty=50)
        second_store_id = self._add_second_store()

        transfer = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 10}],
        })
        assert transfer.status_code == 200, transfer.text

        source_audit = self.session.get(f"{BASE_URL}/api/audit-logs?action=stock_transfer_out").json()
        assert any(r["action"] == "stock_transfer_out" for r in source_audit["data"])

        switch = self.session.post(f"{BASE_URL}/api/users/me/switch-store", json={
            "pharmacy_id": second_store_id})
        assert switch.status_code == 200, switch.text
        dest_audit = self.session.get(f"{BASE_URL}/api/audit-logs?action=stock_transfer_in").json()
        assert any(r["action"] == "stock_transfer_in" for r in dest_audit["data"])


class TestReverseStockTransfer(_Base):
    def _create_transfer(self, qty=30, send_qty=10):
        sku, batch_no = self._create_product_and_batch(qty=qty)
        second_store_id = self._add_second_store()
        transfer = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": send_qty}],
        })
        assert transfer.status_code == 200, transfer.text
        return transfer.json()["id"], second_store_id, sku, batch_no

    def test_reversal_restores_source_and_reduces_destination(self):
        transfer_id, second_store_id, sku, batch_no = self._create_transfer(qty=30, send_qty=10)

        reverse = self.session.post(f"{BASE_URL}/api/stock-transfers/{transfer_id}/reverse")
        assert reverse.status_code == 200, reverse.text

        batches = self.session.get(f"{BASE_URL}/api/stock/batches?product_sku={sku}").json()
        rows = batches.get('data', batches) if isinstance(batches, dict) else batches
        matching = next(b for b in rows if b["batch_no"] == batch_no)
        assert matching["qty_on_hand"] == 30  # back to the original 30

    def test_reversal_rejected_when_already_reversed(self):
        transfer_id, *_ = self._create_transfer()
        first = self.session.post(f"{BASE_URL}/api/stock-transfers/{transfer_id}/reverse")
        assert first.status_code == 200, first.text
        second = self.session.post(f"{BASE_URL}/api/stock-transfers/{transfer_id}/reverse")
        assert second.status_code == 400, second.text

    def test_reversal_rejected_when_destination_stock_already_used(self):
        transfer_id, second_store_id, sku, batch_no = self._create_transfer(qty=30, send_qty=10)

        switch = self.session.post(f"{BASE_URL}/api/users/me/switch-store", json={
            "pharmacy_id": second_store_id})
        assert switch.status_code == 200, switch.text
        sale = self.session.post(f"{BASE_URL}/api/bills", json={
            "status": "paid", "tax_rate": 0, "payment_method": "cash",
            "items": [{
                "product_sku": sku, "batch_no": batch_no, "quantity": 10, "unit_price": 40,
                "disc_percent": 0, "gst_percent": 0,
            }],
        })
        assert sale.status_code == 200, sale.text

        reverse = self.session.post(f"{BASE_URL}/api/stock-transfers/{transfer_id}/reverse")
        assert reverse.status_code == 400, reverse.text


class TestListStockTransfers(_Base):
    def test_lists_transfers_from_both_directions(self):
        sku, batch_no = self._create_product_and_batch(qty=30)
        second_store_id = self._add_second_store()
        transfer = self.session.post(f"{BASE_URL}/api/stock-transfers", json={
            "destination_pharmacy_id": second_store_id,
            "items": [{"product_sku": sku, "batch_number": batch_no, "quantity": 10}],
        })
        assert transfer.status_code == 200, transfer.text

        outbound = self.session.get(f"{BASE_URL}/api/stock-transfers").json()
        assert any(t["direction"] == "out" for t in outbound)

        switch = self.session.post(f"{BASE_URL}/api/users/me/switch-store", json={
            "pharmacy_id": second_store_id})
        assert switch.status_code == 200, switch.text
        inbound = self.session.get(f"{BASE_URL}/api/stock-transfers").json()
        assert any(t["direction"] == "in" for t in inbound)
