/**
 * medicineSeedList — common Indian medicine names + manufacturers, for the
 * Add Medicine autocomplete. Names only, no prices/HSN — those are set per
 * pharmacy. Not exhaustive; a pharmacist can always type something new.
 * dosageForm/category are hints only — the pharmacist confirms/changes them.
 */

export const SEED_MEDICINES = [
  { name: 'Dolo 650',                genericName: 'Paracetamol',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Crocin Advance',          genericName: 'Paracetamol',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Calpol 500',              genericName: 'Paracetamol',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Combiflam',               genericName: 'Ibuprofen + Paracetamol',  dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Brufen 400',              genericName: 'Ibuprofen',                dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Voveran SR',              genericName: 'Diclofenac',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Zerodol P',               genericName: 'Aceclofenac + Paracetamol',dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Azithral 500',            genericName: 'Azithromycin',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Augmentin 625',           genericName: 'Amoxicillin + Clavulanate',dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Amoxyclav 625',           genericName: 'Amoxicillin + Clavulanate',dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Ciplox 500',              genericName: 'Ciprofloxacin',            dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Norflox 400',             genericName: 'Norfloxacin',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Taxim O 200',             genericName: 'Cefixime',                 dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Monocef O',               genericName: 'Cefpodoxime',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Pan 40',                  genericName: 'Pantoprazole',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Pantop 40',               genericName: 'Pantoprazole',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Omez 20',                 genericName: 'Omeprazole',               dosageForm: 'capsule',  category: 'medicine' },
  { name: 'Rantac 150',              genericName: 'Ranitidine',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Digene',                  genericName: 'Antacid',                  dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Gelusil MPS',             genericName: 'Antacid',                  dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Eno',                     genericName: 'Antacid',                  dosageForm: 'powder',   category: 'medicine' },
  { name: 'Cetrizine',               genericName: 'Cetirizine',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Allegra 120',             genericName: 'Fexofenadine',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Avil 25',                 genericName: 'Pheniramine',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Montair LC',              genericName: 'Montelukast + Levocetirizine', dosageForm: 'tablet', category: 'medicine' },
  { name: 'Ascoril LS',              genericName: 'Cough syrup',              dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Benadryl',                genericName: 'Diphenhydramine',          dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Corex',                   genericName: 'Cough syrup',              dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Grilinctus',              genericName: 'Cough syrup',              dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Sinarest',                genericName: 'Cold combination',         dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Vicks Action 500',        genericName: 'Cold combination',         dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Metformin 500',           genericName: 'Metformin',                dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Glycomet 500',            genericName: 'Metformin',                dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Januvia 100',             genericName: 'Sitagliptin',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Amaryl 2',                genericName: 'Glimepiride',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Human Mixtard',           genericName: 'Insulin',                  dosageForm: 'injection',category: 'medicine' },
  { name: 'Telma 40',                genericName: 'Telmisartan',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Amlokind 5',              genericName: 'Amlodipine',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Concor 5',                genericName: 'Bisoprolol',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Ecosprin 75',             genericName: 'Aspirin',                  dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Atorva 10',               genericName: 'Atorvastatin',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Rosuvas 10',              genericName: 'Rosuvastatin',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Shelcal 500',             genericName: 'Calcium + Vitamin D3',     dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Calcirol Sachet',         genericName: 'Vitamin D3',               dosageForm: 'powder',   category: 'medicine' },
  { name: 'Neurobion Forte',         genericName: 'Vitamin B Complex',        dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Becosules',               genericName: 'Vitamin B Complex',        dosageForm: 'capsule',  category: 'medicine' },
  { name: 'Limcee',                  genericName: 'Vitamin C',                dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Zincovit',                genericName: 'Multivitamin',             dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Revital H',               genericName: 'Multivitamin',             dosageForm: 'capsule',  category: 'medicine' },
  { name: 'Livogen',                 genericName: 'Iron + Folic Acid',        dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Folvite 5',               genericName: 'Folic Acid',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Alkasol',                 genericName: 'Alkalinizer',              dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Cyclopam',                genericName: 'Dicyclomine + Paracetamol',dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Meftal Spas',             genericName: 'Mefenamic Acid + Dicyclomine', dosageForm: 'tablet', category: 'medicine' },
  { name: 'Drotin M',                genericName: 'Drotaverine + Mefenamic Acid', dosageForm: 'tablet', category: 'medicine' },
  { name: 'Pudin Hara',              genericName: 'Peppermint oil',           dosageForm: 'capsule',  category: 'medicine' },
  { name: 'Volini Gel',              genericName: 'Diclofenac gel',           dosageForm: 'ointment', category: 'medicine' },
  { name: 'Moov',                    genericName: 'Pain relief balm',         dosageForm: 'ointment', category: 'medicine' },
  { name: 'Betadine Ointment',       genericName: 'Povidone Iodine',          dosageForm: 'ointment', category: 'medicine' },
  { name: 'Soframycin',              genericName: 'Framycetin',               dosageForm: 'ointment', category: 'medicine' },
  { name: 'Candid B Cream',          genericName: 'Clotrimazole + Beclomethasone', dosageForm: 'ointment', category: 'medicine' },
  { name: 'Clobetasol Cream',        genericName: 'Clobetasol',               dosageForm: 'ointment', category: 'medicine' },
  { name: 'Ciplox Eye Drops',        genericName: 'Ciprofloxacin',            dosageForm: 'drops',    category: 'medicine' },
  { name: 'Refresh Tears',           genericName: 'Carboxymethylcellulose',   dosageForm: 'drops',    category: 'medicine' },
  { name: 'Otrivin Nasal Drops',     genericName: 'Xylometazoline',           dosageForm: 'drops',    category: 'medicine' },
  { name: 'Asthalin Inhaler',        genericName: 'Salbutamol',               dosageForm: 'inhaler',  category: 'medicine' },
  { name: 'Foracort Inhaler',        genericName: 'Formoterol + Budesonide',  dosageForm: 'inhaler',  category: 'medicine' },
  { name: 'ORS',                     genericName: 'Oral Rehydration Salts',   dosageForm: 'powder',   category: 'medicine' },
  { name: 'Electral',                genericName: 'Oral Rehydration Salts',   dosageForm: 'powder',   category: 'medicine' },
  { name: 'Duphalac',                genericName: 'Lactulose',                dosageForm: 'syrup',    category: 'medicine' },
  { name: 'Cremaffin',               genericName: 'Liquid Paraffin + Milk of Magnesia', dosageForm: 'syrup', category: 'medicine' },
  { name: 'Ondem 4',                 genericName: 'Ondansetron',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Domstal',                 genericName: 'Domperidone',              dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Alprax 0.25',             genericName: 'Alprazolam',               dosageForm: 'tablet',   category: 'medicine' },
  { name: 'Restyl 0.5',              genericName: 'Alprazolam',               dosageForm: 'tablet',   category: 'medicine' },
];

export const SEED_MANUFACTURERS = [
  'Cipla Ltd', 'Sun Pharmaceutical Industries', "Dr. Reddy's Laboratories", 'Mankind Pharma',
  'Cadila Healthcare (Zydus)', 'Lupin Ltd', 'Alkem Laboratories', 'Torrent Pharmaceuticals',
  'Glenmark Pharmaceuticals', 'Intas Pharmaceuticals', "Dr. Morepen", 'Micro Labs',
  'Abbott India', 'GlaxoSmithKline (GSK) Pharmaceuticals', 'Pfizer Ltd', 'Sanofi India',
  'Novartis India', 'USV Pvt Ltd', 'Ipca Laboratories', 'Emcure Pharmaceuticals',
  'Aristo Pharmaceuticals', 'Macleods Pharmaceuticals', 'Wockhardt Ltd', 'Biocon Ltd',
  'Zuventus Healthcare', 'Ajanta Pharma', 'FDC Ltd', 'Eris Lifesciences',
  'Reckitt Benckiser (India)', 'Johnson & Johnson', 'Procter & Gamble Health',
];
