/**
 * A4BillView — the full-width tax-invoice card BillDetail always rendered
 * before Sep 22, 2026. Extracted unchanged so index.jsx can branch between
 * this and ThermalBillView by Settings > Receipt & Print > Paper Size,
 * instead of always showing this layout regardless of that setting.
 */
import React from 'react';
import { formatDateShort, formatTime } from '@/utils/dates';
import BillItemsTable from './BillItemsTable';
import BillTotals from './BillTotals';
import BillStatusChip from './BillStatusChip';

interface Props {
  bill: any;
  pharmacy: any;
  printSettings: any;
  isParked: boolean;
  gstRows: any[];
  showGstin: boolean;
  showDrugLic: boolean;
  showFssai: boolean;
  showPan: boolean;
  showPatientName: boolean;
  showSignature: boolean;
}

export default function A4BillView({
  bill, pharmacy, printSettings, isParked, gstRows,
  showGstin, showDrugLic, showFssai, showPan, showPatientName, showSignature,
}: Props) {
  return (
    <div
      className="max-w-4xl mx-auto bg-white rounded-xl shadow-sm border border-gray-200 print:shadow-none print:border-none"
      data-testid="bill-view-a4"
    >
      {/* Header */}
      <div className="px-8 pt-8 pb-6 border-b border-gray-100">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">{pharmacy?.pharmacy_name || 'PharmaCare'}</h1>
            {pharmacy?.address  && <p className="text-sm text-gray-500 mt-1">{pharmacy.address}</p>}
            {pharmacy?.city     && <p className="text-sm text-gray-500">{[pharmacy.city, pharmacy.state, pharmacy.pincode].filter(Boolean).join(', ')}</p>}
            {pharmacy?.phone    && <p className="text-sm text-gray-500">📞 {pharmacy.phone}</p>}
            {showGstin   && pharmacy?.gstin        && <p className="text-sm font-medium text-gray-700 mt-1">GSTIN: {pharmacy.gstin}</p>}
            {showDrugLic && pharmacy?.drug_license_number && <p className="text-xs text-gray-500">Drug Lic: {pharmacy.drug_license_number}</p>}
            {showFssai   && pharmacy?.fssai_number && <p className="text-xs text-gray-500">FSSAI: {pharmacy.fssai_number}</p>}
            {showPan     && pharmacy?.pan_number   && <p className="text-xs text-gray-500">PAN: {pharmacy.pan_number}</p>}
            {printSettings?.bill_header && <p className="text-xs text-gray-500 mt-1">{printSettings.bill_header}</p>}
          </div>
          <div className="text-right">
            <div className="text-sm text-gray-500 uppercase tracking-wide font-semibold mb-1">
              {bill.invoice_type === 'PURCHASE' ? 'Purchase Invoice' : 'Tax Invoice'}
            </div>
            {!isParked && <div className="text-2xl font-bold text-brand font-mono">#{bill.bill_number?.replace(/^#/, '')}</div>}
            <BillStatusChip status={bill.status} billNumber={bill.bill_number} />
            <div className="text-sm text-gray-500 mt-2">
              {formatDateShort(bill.created_at)} <span className="text-gray-400">{formatTime(bill.created_at)}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Customer + Doctor */}
      <div className="px-8 py-4 border-b border-gray-100 grid grid-cols-2 gap-8">
        <div>
          <div className="text-xs text-gray-500 uppercase tracking-wide font-semibold mb-2">Bill To</div>
          {showPatientName ? (
            <>
              <div className="font-semibold text-gray-800 text-lg">{bill.customer_name || 'Counter Sale'}</div>
              {bill.customer_mobile && <div className="text-sm text-gray-600 mt-0.5">📞 {bill.customer_mobile}</div>}
            </>
          ) : (
            <div className="text-sm text-gray-400 italic">Patient name hidden</div>
          )}
        </div>
        {bill.doctor_name && (
          <div>
            <div className="text-xs text-gray-500 uppercase tracking-wide font-semibold mb-2">Referred By</div>
            <div className="font-medium text-gray-800">Dr. {bill.doctor_name}</div>
          </div>
        )}
      </div>

      <BillItemsTable items={bill.items} />
      <BillTotals bill={bill} gstRows={gstRows} isParked={isParked} />

      {showSignature && (
        <div className="px-8 pt-6 flex justify-end">
          <div className="text-center text-xs text-gray-600">
            <div className="border-t border-gray-400 w-40 pt-1">Authorised Signatory</div>
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="px-8 py-4 border-t border-gray-100 text-xs text-gray-400">
        {printSettings?.bill_footer && <p className="text-center text-gray-500 mb-1">{printSettings.bill_footer}</p>}
        <div className="flex justify-between items-center">
          <span>Generated by PharmaCare · {new Date().toLocaleString('en-IN')}</span>
          {bill.cashier_name && <span>Billed by: {bill.cashier_name}</span>}
        </div>
      </div>
    </div>
  );
}
