"""add unique constraint on active batch product+batch_number

Revision ID: 29481ee67a4b
Revises: a5b71b3e76b6
Create Date: 2026-09-13 15:16:44.791084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29481ee67a4b'
down_revision: Union[str, None] = 'a5b71b3e76b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'uq_batches_product_batchnumber_active', 'stock_batches', ['product_id', 'batch_number'],
        unique=True, postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_batches_product_batchnumber_active', table_name='stock_batches',
        postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###
