"""add payment_type to purchase_returns

Revision ID: 4227da9b84c7
Revises: 95086fa9b085
Create Date: 2026-09-16 04:57:18.799778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4227da9b84c7'
down_revision: Union[str, None] = '95086fa9b085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows before the NOT NULL applies —
    # autogenerate doesn't add this by itself, and without it this fails
    # against the real dev DB, which already has confirmed purchase returns.
    op.add_column('purchase_returns', sa.Column(
        'payment_type', sa.String(length=20), nullable=False, server_default='credit'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_returns', 'payment_type')
    # ### end Alembic commands ###
