"""add credit_applied_paise to sales_returns

Revision ID: 429dc818b016
Revises: a2deb2ed9744
Create Date: 2026-09-15 17:04:31.744128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429dc818b016'
down_revision: Union[str, None] = 'a2deb2ed9744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' so existing rows (all pre-dating this feature, so
    # none of them applied a credit) backfill safely instead of failing
    # the NOT NULL constraint.
    op.add_column(
        'sales_returns',
        sa.Column('credit_applied_paise', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_returns', 'credit_applied_paise')
    # ### end Alembic commands ###
