"""doctors: add notes column

Revision ID: 4ef3a1f0aec2
Revises: bcd3c6cd10e2
Create Date: 2026-09-13 05:18:08.318417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef3a1f0aec2'
down_revision: Union[str, None] = 'bcd3c6cd10e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'notes')
    # ### end Alembic commands ###
