"""make sales_returns original_bill_id and sales_return_items bill_item_id nullable

Revision ID: 95086fa9b085
Revises: 429dc818b016
Create Date: 2026-09-15 18:17:14.685019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95086fa9b085'
down_revision: Union[str, None] = '429dc818b016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_return_items', 'bill_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sales_returns', 'original_bill_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_returns', 'original_bill_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales_return_items', 'bill_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
