"""initial_schema

Revision ID: 95d13d1508dc
Revises: 
Create Date: 2026-04-11 15:00:37.402484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95d13d1508dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('drug_license_number', sa.String(length=50), nullable=True),
    sa.Column('drug_license_expiry', sa.Date(), nullable=True),
    sa.Column('fssai_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('alternate_phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('credit_limit_paise', sa.Integer(), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('outstanding_paise', sa.Integer(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_name', 'customers', ['pharmacy_id', 'name'], unique=False)
    op.create_index('idx_customers_pharmacy', 'customers', ['pharmacy_id'], unique=False)
    op.create_index('idx_customers_phone', 'customers', ['pharmacy_id', 'phone'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('hospital', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doctors_name', 'doctors', ['pharmacy_id', 'name'], unique=False)
    op.create_index('idx_doctors_pharmacy', 'doctors', ['pharmacy_id'], unique=False)
    op.create_table('pharmacy_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('bill_prefix', sa.String(length=10), nullable=False),
    sa.Column('bill_sequence_number', sa.Integer(), nullable=False),
    sa.Column('bill_number_length', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold_days', sa.Integer(), nullable=False),
    sa.Column('near_expiry_threshold_days', sa.Integer(), nullable=False),
    sa.Column('default_gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('print_logo', sa.Boolean(), nullable=False),
    sa.Column('print_drug_license', sa.Boolean(), nullable=False),
    sa.Column('print_patient_name', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('generic_name', sa.String(length=300), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('drug_schedule', sa.String(length=20), nullable=False),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('pack_size', sa.String(length=100), nullable=True),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('requires_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'sku')
    )
    op.create_index('idx_products_active', 'products', ['pharmacy_id', 'is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_products_barcode', 'products', ['pharmacy_id', 'barcode'], unique=False)
    op.create_index('idx_products_generic', 'products', ['pharmacy_id', 'generic_name'], unique=False)
    op.create_index('idx_products_name', 'products', ['pharmacy_id', 'name'], unique=False)
    op.create_index('idx_products_pharmacy', 'products', ['pharmacy_id'], unique=False)
    op.create_index('idx_products_schedule', 'products', ['pharmacy_id', 'drug_schedule'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('alternate_phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('drug_license_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit_paise', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppliers_pharmacy', 'suppliers', ['pharmacy_id'], unique=False)
    op.create_table('stock_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('mrp_paise', sa.Integer(), nullable=False),
    sa.Column('cost_price_paise', sa.Integer(), nullable=False),
    sa.Column('sale_price_paise', sa.Integer(), nullable=True),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('quantity_written_off', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batches_active', 'stock_batches', ['product_id', 'quantity_on_hand'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_batches_expiry', 'stock_batches', ['pharmacy_id', 'expiry_date'], unique=False)
    op.create_index('idx_batches_product', 'stock_batches', ['product_id'], unique=False)
    op.create_index('idx_batches_quantity', 'stock_batches', ['product_id', 'quantity_on_hand'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_pharmacy', 'audit_logs', ['pharmacy_id'], unique=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('bill_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('bill_time', sa.Time(timezone=True), server_default=sa.text('CURRENT_TIME'), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=10), nullable=True),
    sa.Column('customer_gstin', sa.String(length=15), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('prescription_number', sa.String(length=100), nullable=True),
    sa.Column('prescription_date', sa.Date(), nullable=True),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('mrp_total_paise', sa.Integer(), nullable=False),
    sa.Column('item_discount_paise', sa.Integer(), nullable=False),
    sa.Column('bill_discount_paise', sa.Integer(), nullable=False),
    sa.Column('bill_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_discount_paise', sa.Integer(), nullable=False),
    sa.Column('taxable_amount_paise', sa.Integer(), nullable=False),
    sa.Column('total_cgst_paise', sa.Integer(), nullable=False),
    sa.Column('total_sgst_paise', sa.Integer(), nullable=False),
    sa.Column('total_igst_paise', sa.Integer(), nullable=False),
    sa.Column('total_gst_paise', sa.Integer(), nullable=False),
    sa.Column('grand_total_paise', sa.Integer(), nullable=False),
    sa.Column('amount_paid_paise', sa.Integer(), nullable=False),
    sa.Column('balance_paise', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('cost_total_paise', sa.Integer(), nullable=False),
    sa.Column('margin_paise', sa.Integer(), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('billed_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'bill_number')
    )
    op.create_index('idx_bills_customer', 'bills', ['customer_id'], unique=False)
    op.create_index('idx_bills_date', 'bills', ['pharmacy_id', 'bill_date'], unique=False)
    op.create_index('idx_bills_due', 'bills', ['pharmacy_id'], unique=False, postgresql_where=sa.text("status = 'due'"))
    op.create_index('idx_bills_number', 'bills', ['pharmacy_id', 'bill_number'], unique=False)
    op.create_index('idx_bills_paid', 'bills', ['pharmacy_id', 'bill_date'], unique=False, postgresql_where=sa.text("status = 'paid'"))
    op.create_index('idx_bills_pharmacy', 'bills', ['pharmacy_id'], unique=False)
    op.create_index('idx_bills_status', 'bills', ['pharmacy_id', 'status'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('grn_number', sa.String(length=50), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('total_discount_paise', sa.Integer(), nullable=False),
    sa.Column('total_gst_paise', sa.Integer(), nullable=False),
    sa.Column('total_cgst_paise', sa.Integer(), nullable=False),
    sa.Column('total_sgst_paise', sa.Integer(), nullable=False),
    sa.Column('total_igst_paise', sa.Integer(), nullable=False),
    sa.Column('grand_total_paise', sa.Integer(), nullable=False),
    sa.Column('amount_paid_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'purchase_number')
    )
    op.create_index('idx_purchases_date', 'purchases', ['pharmacy_id', 'purchase_date'], unique=False)
    op.create_index('idx_purchases_pharmacy', 'purchases', ['pharmacy_id'], unique=False)
    op.create_index('idx_purchases_status', 'purchases', ['pharmacy_id', 'status'], unique=False)
    op.create_index('idx_purchases_supplier', 'purchases', ['supplier_id'], unique=False)
    op.create_index('idx_purchases_unpaid', 'purchases', ['pharmacy_id'], unique=False, postgresql_where=sa.text("payment_status = 'unpaid'"))
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movements_batch', 'stock_movements', ['batch_id'], unique=False)
    op.create_index('idx_movements_pharmacy', 'stock_movements', ['pharmacy_id', 'created_at'], unique=False)
    op.create_index('idx_movements_product', 'stock_movements', ['product_id'], unique=False)
    op.create_index('idx_movements_reference', 'stock_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('generic_name', sa.String(length=300), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('drug_schedule', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('mrp_paise', sa.Integer(), nullable=False),
    sa.Column('sale_price_paise', sa.Integer(), nullable=False),
    sa.Column('cost_price_paise', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_paise', sa.Integer(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable_amount_paise', sa.Integer(), nullable=False),
    sa.Column('cgst_paise', sa.Integer(), nullable=False),
    sa.Column('sgst_paise', sa.Integer(), nullable=False),
    sa.Column('igst_paise', sa.Integer(), nullable=False),
    sa.Column('gst_paise', sa.Integer(), nullable=False),
    sa.Column('line_total_paise', sa.Integer(), nullable=False),
    sa.Column('line_cost_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bill_items_batch', 'bill_items', ['batch_id'], unique=False)
    op.create_index('idx_bill_items_bill', 'bill_items', ['bill_id'], unique=False)
    op.create_index('idx_bill_items_product', 'bill_items', ['product_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('units_per_pack', sa.Integer(), nullable=False),
    sa.Column('mrp_paise', sa.Integer(), nullable=False),
    sa.Column('cost_price_paise', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxable_amount_paise', sa.Integer(), nullable=False),
    sa.Column('gst_amount_paise', sa.Integer(), nullable=False),
    sa.Column('line_total_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purchase_items_product', 'purchase_items', ['product_id'], unique=False)
    op.create_index('idx_purchase_items_purchase', 'purchase_items', ['purchase_id'], unique=False)
    op.create_table('purchase_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('return_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('return_reason', sa.String(length=50), nullable=False),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('total_gst_paise', sa.Integer(), nullable=False),
    sa.Column('grand_total_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_note_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'return_number')
    )
    op.create_table('sales_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('original_bill_id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=50), nullable=False),
    sa.Column('return_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('total_gst_paise', sa.Integer(), nullable=False),
    sa.Column('grand_total_paise', sa.Integer(), nullable=False),
    sa.Column('refund_method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'return_number')
    )
    op.create_table('purchase_return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_return_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price_paise', sa.Integer(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount_paise', sa.Integer(), nullable=False),
    sa.Column('line_total_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sales_return_id', sa.UUID(), nullable=False),
    sa.Column('bill_item_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price_paise', sa.Integer(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_paise', sa.Integer(), nullable=False),
    sa.Column('line_total_paise', sa.Integer(), nullable=False),
    sa.Column('return_to_stock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['bill_item_id'], ['bill_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_h1_register',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('bill_item_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('prescriber_name', sa.String(length=200), nullable=False),
    sa.Column('prescriber_registration_number', sa.String(length=100), nullable=True),
    sa.Column('prescriber_address', sa.Text(), nullable=True),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_address', sa.Text(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('supply_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('dispensed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['bill_item_id'], ['bill_items.id'], ),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_h1_date', 'schedule_h1_register', ['pharmacy_id', 'supply_date'], unique=False)
    op.create_index('idx_h1_pharmacy', 'schedule_h1_register', ['pharmacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_h1_pharmacy', table_name='schedule_h1_register')
    op.drop_index('idx_h1_date', table_name='schedule_h1_register')
    op.drop_table('schedule_h1_register')
    op.drop_table('sales_return_items')
    op.drop_table('purchase_return_items')
    op.drop_table('sales_returns')
    op.drop_table('purchase_returns')
    op.drop_table('purchase_payments')
    op.drop_index('idx_purchase_items_purchase', table_name='purchase_items')
    op.drop_index('idx_purchase_items_product', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('idx_bill_items_product', table_name='bill_items')
    op.drop_index('idx_bill_items_bill', table_name='bill_items')
    op.drop_index('idx_bill_items_batch', table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('idx_movements_reference', table_name='stock_movements')
    op.drop_index('idx_movements_product', table_name='stock_movements')
    op.drop_index('idx_movements_pharmacy', table_name='stock_movements')
    op.drop_index('idx_movements_batch', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('idx_purchases_unpaid', table_name='purchases', postgresql_where=sa.text("payment_status = 'unpaid'"))
    op.drop_index('idx_purchases_supplier', table_name='purchases')
    op.drop_index('idx_purchases_status', table_name='purchases')
    op.drop_index('idx_purchases_pharmacy', table_name='purchases')
    op.drop_index('idx_purchases_date', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('idx_bills_status', table_name='bills')
    op.drop_index('idx_bills_pharmacy', table_name='bills')
    op.drop_index('idx_bills_paid', table_name='bills', postgresql_where=sa.text("status = 'paid'"))
    op.drop_index('idx_bills_number', table_name='bills')
    op.drop_index('idx_bills_due', table_name='bills', postgresql_where=sa.text("status = 'due'"))
    op.drop_index('idx_bills_date', table_name='bills')
    op.drop_index('idx_bills_customer', table_name='bills')
    op.drop_table('bills')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_index('idx_audit_logs_pharmacy', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index('idx_batches_quantity', table_name='stock_batches')
    op.drop_index('idx_batches_product', table_name='stock_batches')
    op.drop_index('idx_batches_expiry', table_name='stock_batches')
    op.drop_index('idx_batches_active', table_name='stock_batches', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('stock_batches')
    op.drop_index('idx_suppliers_pharmacy', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_index('idx_products_schedule', table_name='products')
    op.drop_index('idx_products_pharmacy', table_name='products')
    op.drop_index('idx_products_name', table_name='products')
    op.drop_index('idx_products_generic', table_name='products')
    op.drop_index('idx_products_barcode', table_name='products')
    op.drop_index('idx_products_active', table_name='products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('products')
    op.drop_table('pharmacy_settings')
    op.drop_index('idx_doctors_pharmacy', table_name='doctors')
    op.drop_index('idx_doctors_name', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('idx_customers_phone', table_name='customers')
    op.drop_index('idx_customers_pharmacy', table_name='customers')
    op.drop_index('idx_customers_name', table_name='customers')
    op.drop_table('customers')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
