"""add day_end_closings table

Revision ID: a2deb2ed9744
Revises: ecd0d70d26f5
Create Date: 2026-09-15 13:52:32.345662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2deb2ed9744'
down_revision: Union[str, None] = 'ecd0d70d26f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_end_closings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('expected_cash_paise', sa.Integer(), nullable=False),
    sa.Column('counted_cash_paise', sa.Integer(), nullable=False),
    sa.Column('variance_paise', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'closing_date')
    )
    op.create_index('idx_day_end_pharmacy_date', 'day_end_closings', ['pharmacy_id', 'closing_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_day_end_pharmacy_date', table_name='day_end_closings')
    op.drop_table('day_end_closings')
    # ### end Alembic commands ###
