"""add credit status tracking to purchase returns

Revision ID: a5b71b3e76b6
Revises: c27e2d4f63ae
Create Date: 2026-09-13 12:57:15.287062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b71b3e76b6'
down_revision: Union[str, None] = 'c27e2d4f63ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default added by hand (autogenerate leaves it off) so existing
    # purchase_returns rows get "pending"/0 instead of failing the NOT
    # NULL constraint on this ALTER TABLE.
    op.add_column('purchase_returns', sa.Column(
        'credit_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('purchase_returns', sa.Column(
        'credit_received_paise', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_returns', 'credit_received_paise')
    op.drop_column('purchase_returns', 'credit_status')
    # ### end Alembic commands ###
