"""drop unused customers.loyalty_points column

Revision ID: b26fb010316e
Revises: 25ea9247b0c3
Create Date: 2026-09-12 12:19:28.228565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26fb010316e'
down_revision: Union[str, None] = '25ea9247b0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'loyalty_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('loyalty_points', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
