"""customers: add notes, drop unused outstanding_paise (compute on read)

Revision ID: bcd3c6cd10e2
Revises: b26fb010316e
Create Date: 2026-09-12 12:33:45.321894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd3c6cd10e2'
down_revision: Union[str, None] = 'b26fb010316e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('customers', 'outstanding_paise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('outstanding_paise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('customers', 'notes')
    # ### end Alembic commands ###
