"""add billing and returns preference columns to pharmacy_settings

Revision ID: c27e2d4f63ae
Revises: 4ef3a1f0aec2
Create Date: 2026-09-13 10:32:18.197548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27e2d4f63ae'
down_revision: Union[str, None] = '4ef3a1f0aec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default added by hand (autogenerate leaves it off) so existing
    # pharmacy_settings rows get the same defaults the ORM model declares,
    # instead of failing the NOT NULL constraint on this ALTER TABLE.
    op.add_column('pharmacy_settings', sa.Column('enable_draft_bills', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('pharmacy_settings', sa.Column('auto_print_invoice', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pharmacy_settings', sa.Column('return_window_days', sa.Integer(), nullable=False, server_default='7'))
    op.add_column('pharmacy_settings', sa.Column('require_original_bill', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pharmacy_settings', sa.Column('allow_partial_return', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_settings', 'allow_partial_return')
    op.drop_column('pharmacy_settings', 'require_original_bill')
    op.drop_column('pharmacy_settings', 'return_window_days')
    op.drop_column('pharmacy_settings', 'auto_print_invoice')
    op.drop_column('pharmacy_settings', 'enable_draft_bills')
    # ### end Alembic commands ###
