"""add stock_transfers and stock_transfer_items

Revision ID: e3511cb2db2b
Revises: 3bc60ce0ce95
Create Date: 2026-09-26 16:26:25.536735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3511cb2db2b'
down_revision: Union[str, None] = '3bc60ce0ce95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('source_pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('destination_pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('is_cross_gstin', sa.Boolean(), nullable=False),
    sa.Column('source_gstin', sa.String(length=15), nullable=True),
    sa.Column('destination_gstin', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('reversed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_pharmacy_id', 'transfer_number')
    )
    op.create_index('idx_stock_transfers_destination', 'stock_transfers', ['destination_pharmacy_id'], unique=False)
    op.create_index('idx_stock_transfers_source', 'stock_transfers', ['source_pharmacy_id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_price_paise', sa.Integer(), nullable=False),
    sa.Column('mrp_paise', sa.Integer(), nullable=False),
    sa.Column('source_batch_id', sa.UUID(), nullable=False),
    sa.Column('destination_batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_transfer_items_transfer', 'stock_transfer_items', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_transfer_items_transfer', table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index('idx_stock_transfers_source', table_name='stock_transfers')
    op.drop_index('idx_stock_transfers_destination', table_name='stock_transfers')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
