"""add payment reversal columns to purchase_payments

Revision ID: ecd0d70d26f5
Revises: 29481ee67a4b
Create Date: 2026-09-13 15:21:32.432749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd0d70d26f5'
down_revision: Union[str, None] = '29481ee67a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_payments', sa.Column('reversed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('purchase_payments', sa.Column('reversed_by', sa.UUID(), nullable=True))
    op.add_column('purchase_payments', sa.Column('reversal_reason', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_purchase_payments_reversed_by_users', 'purchase_payments', 'users',
        ['reversed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_purchase_payments_reversed_by_users', 'purchase_payments', type_='foreignkey')
    op.drop_column('purchase_payments', 'reversal_reason')
    op.drop_column('purchase_payments', 'reversed_by')
    op.drop_column('purchase_payments', 'reversed_at')
    # ### end Alembic commands ###
