"""add is_returnable to products

Revision ID: f98d8a9caeee
Revises: 2e45f4808592
Create Date: 2026-09-19 15:53:21.688805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98d8a9caeee'
down_revision: Union[str, None] = '2e45f4808592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default added by hand — autogenerate left this NOT NULL with no
    # default, which fails outright against any table with existing rows.
    # Defaults every existing product to returnable (True), the documented
    # default in models/products.py; a pharmacist marks the real exceptions.
    op.add_column('products', sa.Column(
        'is_returnable', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_returnable')
    # ### end Alembic commands ###
